import { readFileSync } from 'fs'
import { join } from 'path'

const read = (rel) => readFileSync(join(process.cwd(), rel), 'utf8')

describe('Featured parlay persist contract — Phase B', () => {
  test('generate persists Featured only and leaves explorer unsaved', () => {
    const route = read('app/api/parlays/generate/route.js')
    expect(route).toMatch(/persistFeaturedClearedParlays/)
    expect(route).toMatch(/persistFeaturedIfNeeded/)
    expect(route).toMatch(/loadFeaturedSnapshotCard/)
    expect(route).toMatch(/resolveFeaturedGenerate/)
    expect(route).toMatch(/Explorer generate never writes/)
    expect(route).toMatch(/Featured-cleared cards snapshot/)
    expect(route).toMatch(/isFeatured\s*\n\s*\? await resolveFeaturedGenerate/)
    expect(route).toMatch(/featured\s*\n\s*\? await resolveFeaturedGenerate/)
    expect(route).not.toMatch(/Parlay saving temporarily disabled/)
    expect(route).not.toMatch(/saveParlaysToSupabase/)
  })

  test('save is a retired 410 no-op and never persists Featured from the client', () => {
    const save = read('app/api/parlays/save/route.js')
    expect(save).toMatch(/gone\(/)
    expect(save).toMatch(/Client parlay saves are retired/)
    expect(save).not.toMatch(/persistFeaturedClearedParlay/)
    expect(save).not.toMatch(/User saved parlay with/)
  })

  test('history and validate stay on the Featured cohort tag', () => {
    const history = read('app/api/parlays/history/route.js')
    const validate = read('app/api/parlays/validate/route.js')
    expect(history).toMatch(/FEATURED_COHORT_TAG/)
    expect(history).toMatch(/dedupeFeaturedCohortRows/)
    expect(history).toMatch(/filterFeaturedCohortRows/)
    expect(history).toMatch(/summarizeFeaturedParlays/)
    expect(history).toMatch(/attachFeaturedHistoryLegDisplay/)
    expect(history).toMatch(/cohort: 'featured'/)
    expect(history).toMatch(/fetchFeaturedPropValidations/)
    expect(history).not.toMatch(/validations\.find\(\(row\) =>/)
    expect(validate).toMatch(/FEATURED_COHORT_TAG/)
    expect(validate).toMatch(/dedupeFeaturedCohortRows/)
    expect(validate).toMatch(/gradeFeaturedParlayFromValidations/)
    expect(validate).toMatch(/filterFeaturedCohortRows/)
    expect(validate).toMatch(/fetchFeaturedPropValidations/)
    expect(validate).toMatch(/fetchAllPages/)

    const query = read('lib/featured-validation-query.js')
    expect(query).toMatch(/\.in\('playerName', playerNames\)/)
    expect(query).toMatch(/\.in\('gameIdRef', gameIdRefs\)/)
    expect(query).toMatch(/order\('id', \{ ascending: true \}\)/)
    expect(query).toMatch(/range\(from, to\)/)

    const autoValidate = read('scripts/auto-validate-parlays.js')
    expect(autoValidate).toMatch(/gradeFeaturedParlayFromValidations/)
    expect(autoValidate).toMatch(/isFeaturedCohortRow/)
  })

  test('persist layer does not write extra PropValidation rows', () => {
    const persist = read('lib/featured-parlay-persist.js')
    expect(persist).not.toMatch(/recordPropPrediction/)
    expect(persist).toMatch(/Does not insert extra PropValidation/)
    expect(persist).toMatch(/featuredPersistWritePlan/)
    expect(persist).toMatch(/featuredPersistClaim/)
    expect(persist).toMatch(/deleteParlay/)
    expect(persist).toMatch(/normalizeFeaturedSnapshotSport/)
    expect(persist).toMatch(/sport_not_published/)
  })

  test('history UI is honest empty and labeled Featured-cleared', () => {
    const history = read('components/ParlayHistory.js')
    const page = read('app/parlays/page.js')
    const results = read('components/ParlayResults.js')
    expect(history).toMatch(/Featured Parlay Track/)
    expect(history).toMatch(/No Featured-cleared parlays yet/)
    expect(history).toMatch(/Empty until a Published-eligible 3-leg card clears Featured/)
    expect(history).toMatch(/resolveFeaturedHistoryLegOutcome/)
    expect(history).toMatch(/featuredHistoryLegActual/)
    expect(history).not.toMatch(/legResult === 'correct'/)
    expect(history).not.toMatch(/No saved parlays yet/)
    expect(page).toMatch(/onFeaturedReady/)
    expect(page).toMatch(/Featured track/)
    expect(page).toMatch(/dedupeFeaturedPageCards/)
    expect(page).toMatch(/formatAmericanOdds/)
    expect(page).not.toMatch(/Save &amp; Track<\/span> any parlay/)
    expect(results).toMatch(/isFeaturedWorthyParlay/)
    expect(results).toMatch(/Explorer — not tracked/)
    expect(results).toMatch(/Featured track is filled at generate/)
    expect(results).not.toMatch(/\/api\/parlays\/save/)
    expect(results).not.toMatch(/Save to Featured track/)
  })

  test('ops script snapshots Featured without calling The Odds API', () => {
    const script = read('scripts/record-featured-parlays.js')
    const pkg = read('package.json')
    expect(script).toMatch(/does not call The Odds API/)
    expect(script).toMatch(/generateSimpleParlays/)
    expect(script).toMatch(/persistFeaturedClearedParlays/)
    expect(script).toMatch(/featured: true/)
    expect(pkg).toMatch(/"record:featured": "node scripts\/record-featured-parlays\.js"/)
    expect(pkg).toMatch(/"cleanup:featured-dupes": "node scripts\/cleanup-duplicate-featured-parlays\.js"/)
    expect(pkg).toMatch(/"report:featured-game-mismatch": "node scripts\/report-featured-game-mismatch\.js"/)
    expect(pkg).toMatch(/"report:odds-format": "node scripts\/report-odds-format-ambiguity\.js"/)
    const mismatch = read('scripts/report-featured-game-mismatch.js')
    expect(mismatch).toMatch(/reportFeaturedGameMismatchGrades/)
    expect(mismatch).toMatch(/Does not write/)
    expect(mismatch).toMatch(/fetchFeaturedPropValidations/)
    const cleanup = read('scripts/cleanup-duplicate-featured-parlays.js')
    expect(cleanup).toMatch(/planFeaturedDuplicateCleanup/)
    expect(cleanup).toMatch(/--apply/)
    expect(cleanup).toMatch(/Dry-run/)
    expect(cleanup).toMatch(/Does not call The Odds API/)
  })
})
